//products
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const SET_PRODUCTS_PENDING_STATUS = 'SET_PRODUCTS_PENDING_STATUS'
export const SET_SPECIFIC_PRODUCT = 'SET_SPECIFIC_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const SET_NEW_PRODUCT = 'SET_NEW_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

//pagination
export const ON_CHANGE_PAGINATION = 'ON_CHANGE_PAGINATION'

//search
export const SET_QUERY = 'SET_QUERY'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'

//user
export const SET_LOGIN_USER = 'SET_LOGIN_USER'
export const SET_USER_REDIRECT = 'SET_USER_REDIRECT'

//socket

export const START_LISTEN_ON_URL = 'START_LISTEN_ON_URL'
export const CHANGE_AMOUNT_OF_PRODUCT = 'CHANGE_AMOUNT_OF_PRODUCT'
export const SOCKET_PENDING_STATUS = 'SOCKET_PENDING_STATUS'
export const SOCKET_HAS_BEEN_CONNECTED = 'SOCKET_HAS_BEEN_CONNECTED'

//socket events

export const BID_UPDATE = 'BID_UPDATE'
export const SOCKET_HAS_BEEN_DISCONNECTED = 'SOCKET_HAS_BEEN_DISCONNECTED'
export const ON_ADD_NEW_PRODUCT = 'ON_ADD_NEW_PRODUCT'
export const ON_REMOVE_PRODUCT = 'ON_REMOVE_PRODUCT'